arch: amd64
os: linux
dist: focal

language: php
php:
  - '7.3'
  - '7.4'
  - '8.0'

before_script:
  - phpize
  - ./configure
  - make

script:
  - make test REPORT_EXIT_STATUS=1 NO_INTERACTION=1 TRAVIS=0
